server:
  port: ${server_port:8080}
  servlet:
    context-path: /api
spring:
  application:
    name: web_test
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testDb
    username: testUser
    password: testUser
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
