server:
  port: ${server_port:8080}
  servlet:
    context-path: /api
spring:
  application:
    name: web_test
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
    url: jdbc:h2:mem:testDb
    username: testUser
    password: testUser
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
